"""Pin starts to be int

Revision ID: 17f03aa10cf0
Revises: e47660b5613c
Create Date: 2023-08-15 16:26:19.383982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17f03aa10cf0'
down_revision: Union[str, None] = 'e47660b5613c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('Password', 'password',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Password', 'password',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
