"""some corrects

Revision ID: 7a5146d59b54
Revises: be07588c329e
Create Date: 2023-08-15 12:32:47.178588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a5146d59b54'
down_revision: Union[str, None] = 'be07588c329e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Password', 'special_chars')
    op.drop_column('Password', 'hard_mode')
    op.drop_column('Password', 'digits')
    op.drop_column('Password', 'length')
    op.drop_column('Password', 'uppercase_chars')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
