"""New table 'PinCode'

Revision ID: e47660b5613c
Revises: 7a5146d59b54
Create Date: 2023-08-15 14:47:39.119827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e47660b5613c'
down_revision: Union[str, None] = '7a5146d59b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pin-Code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pin', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade() -> None:
    pass
